os: osx

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
  - gem install fastlane
  - ./flutter/bin/flutter build ios --release --no-codesign
  - cd ios && fastlane init


